### ISSUE TITLE
关于python-c-api的问题

### ISSUE THREAD

**Issue by JohnnyY8** [chenzhiwei/linux#3]
您好：
       我是厦门大学的一名学生，最近在学习如何让Python调用C++函数，网上看到您的blog写了一些教程（https://github.com/chenzhiwei/linux/blob/master/python/python-c-api.md），顶礼膜拜，成功调用了一些，也留下了一点问题，想向您请教一下。
       我的代码想返回两个PyObject *变量，我的想法是构造一个List返回，但是失败了，如果只返回一个是成功了，所以想向您请教一下，我的代码是不是有什么问题？

    PyObject* ret_list = NULL;
    flow_x_gpu.download( flow_x );
    flow_y_gpu.download( flow_y );
    cout << "downloading..." << endl;
    PyObject* fx = cvt.toNDArray(flow_x);
    PyObject* fy = cvt.toNDArray(flow_y);
    PyList_SetItem(ret_list, 0, fx); // 这里没有办法成功貌似，因为没有办法输出下面的“returning”字符串
    PyList_SetItem(ret_list, 1, fy); // 这里没有办法成功貌似，因为没有办法输出下面的“returning”字符串
    cout << "returning..." << endl;
    return ret_list;
    //return cvt.toNDArray(flow_x); 如果只返回这一个变量是可以成功的

    编译可以过，但是执行就卡住了，不知您可否指点一二。

**Comment by chenzhiwei** [comment]
这类问题建议发邮件给我，谢谢！
